Open API環境構築(CNV-66)
Conovel/backend pull request #4
Opened 2024-09-21 08:39 UTC by ryo-i

## JIRAチケットURL
https://techno-kuro-novel.atlassian.net/browse/CNV-66

---
## 実装内容

- OpenAPI generatorの動作確認のため、該当なし
- 実際に使うAPIを実装時に本件のAPI設定は削除する予定

参考url
[OpenAPI generatorを試してみる - Qiita](https://qiita.com/amuyikam/items/e8a45daae59c68be0fc8)

### 機能要件

このセクションでは、以下URL参照先（機能要件）の記載を引用し、どの要件を満たすための実装をしたのかを記載します。
https://techno-kuro-novel.atlassian.net/wiki/spaces/Conovel/pages/3145744
なお、上記URLに含まれない実装をしている場合は、適宜参照先URLを付して、記載を引用して記載してください。
必ず製造タスクの根拠を示してください。

- OpenAPI generatorの動作確認のため、該当なし
- 実際に使うAPIを実装時に本件のAPI設定は削除する予定

参考url
[OpenAPI generatorを試してみる - Qiita](https://qiita.com/amuyikam/items/e8a45daae59c68be0fc8)

### 非機能要件

このセクションでは、以下URL参照先（非機能要件）の記載を引用し、どの要件を満たすための実装をしたのかを記載します。
https://techno-kuro-novel.atlassian.net/wiki/spaces/Conovel/pages/1376286/_PJ
なお、上記URLに含まれない実装をしている場合は、適宜参照先URLを付して、記載を引用して記載してください。

- 機能要件1：`セキュリティ/CORS 制約は、同一ドメインのみとし、他ドメインからのREST要求を受け付けないこと`
  - frontend側（ブラウザ`localhost:3000`）からbackend側の`http://localhost:3001/v1/pets/`にリクエスト
  - ドメインが異なるためCORSが発生
  - `rack-cors`をインストール
  - `config/initializers/cors.rb`内で`localhost:3000`のみ許可する設定
  - CORS解消
- 機能要件2：`テスト定義/UT/バック/RSpec による パラメタ網羅、分岐網羅、APIコール網羅とする（C1 テスト）`
  - rspecでrswagの`run_test`を実行し、成功
- 機能要件3：`計画書/API設計/OpenAPI を利用し、Github管理とする`
  - environmentのconovel-openapi.ymlをもとにopenapigenディレクトリにruby-on-railsファイル一式を生成
  - ruby-on-railsを参考にrails環境にAPI設定を適用
  - 動作確認
  - rswagをインストール
  - rswagでSwaggerUIドキュメントを生成

以下非機能要件を遵守すべき事項を確認しチェック
[○] CORS制約
[] XSS防止
[] CSRF防止
[] 認証中トークン
[] 広告枠

---

## テスト

[-] テストコード作成済み（C1レベル確認済み）

※テストコードは作成したが、open-api動作確認のための簡易的なもの

## 自身で確認した動作のエビデンス（スクショ等）

### 動作確認エビデンス1
`http://localhost:3001/v1/pets/`をブラウザで開くと想定されるレスポンス`[{"id":1,"name":"コノベル太郎"}]`が表示される
![スクリーンショット 2024-09-21 17 35 46](https://github.com/user-attachments/assets/f2256cd8-e653-4300-9770-fa102e8bb943)

### 動作確認エビデンス2
postmanで`http://localhost:3001/v1/pets/`を開くとAPI通信が200成功になっている
![スクリーンショット 2024-09-21 17 37 13](https://github.com/user-attachments/assets/95aa69d2-2545-471c-81dc-ef857d1af66b)
![スクリーンショット 2024-09-21 17 37 43](https://github.com/user-attachments/assets/4ed03ce2-8589-4831-9835-132b5a8b6c1f)

### 動作確認エビデンス3
`http://localhost:3001/api-docs/index.html`を開くとSwaggerUIドキュメントが表示される
![スクリーンショット 2024-09-21 17 39 12](https://github.com/user-attachments/assets/246c9124-af51-4f4b-aea5-ab3bb2097e83)

---
## 結合テスト・受入テストに持ち越すテスト項目（必ず1つ以上作成）
本PullReqで洗い出し記載して、Mergeしたら、以下に整理転記する
https://techno-kuro-novel.atlassian.net/wiki/spaces/Conovel/pages/38567991

### テスト要求1

### テスト要求2

### テスト要求3

2024-09-22 10:10 UTC, technokuro reviewed
@ryo-i 
一部コメントしました
やはり、今回の動作確認要のものが、本番領域に含まれている箇所があるので、それを @ryo-i さんが把握していさえすればいいと思いました。

2024-09-22 10:10 UTC, technokuro commented on config/initializers/cors.rb
> +    origins 'http://localhost:3000' # localhost frontend url
@ryo-i 
ここは `config` を参照させたいですね。
`production` と `development` で定義分けしたいです

ちなみに、本番ドメインは `conovel.jp` です

以下例です

```production.rb
Rails.application.configure do
  config.origin_url = ENV['PRODUCTION_ORIGIN_URL'] || 'https://conovel.jp'
```

```development.rb
Rails.application.configure do
  config.origin_url = ENV['DEVELOPMENT_ORIGIN_URL'] || 'https://localhost:3000'
```

2024-09-22 10:57 UTC, azufb requested changes
@ryo-i 
CC： @technokuro 
くろさんがすでにコメントして頂いているものと同じような内容にはなりますが、1点コメントいたしました！
ご確認お願いいたします！

2024-09-22 10:57 UTC, azufb commented on openapigen/config/cable.yml
> +  url: redis://localhost:6379/1
@ryo-i 
CC： @technokuro 
こちらについても、localhostになっていて、環境変数で管理する方が良いのでは？と思いました！！

2024-09-23 05:29 UTC, ryo-i reviewed
@technokuro 
修正しました！ご確認お願いしますmm

@azufb 
openapiディレクトリ内のファイルでRails本体には影響ない箇所でした。
ただ、Raisl本体にも同様のlocalhostの記載がありましたので、このポート番号の意味（Redis設定）などについて調べてみました。ご確認お願いしますmm

2024-09-23 05:29 UTC, ryo-i commented on openapigen/config/cable.yml
> +  url: redis://localhost:6379/1
@azufb cc @technokuro 
ありがとうございます！
こちらのファイルについてちゃんと理解していなかったため、調べてみましたmm

- `openapigen/config/cable.yml`（`openapigen`ディレクトリ以下のファイル一式）はopenapi-generatorで自動的に生成されたファイル
- そのうち`cable.yml`については上位階層のRails本体`config/cable.yml`には反映していない
- Rails本体`/config/cable.yml`にも同様のlocalhostの記述があり（今回の修正では触っていないためRails環境構築時に自動的に生成されたと思われる）
https://github.com/Conovel/backend/blob/feature/CNV-66-open-api/config/cable.yml
```yml
production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: backend_production
```
- 上記環境変数`REDIS_URL`が設定されていない場合にのみ`localhost`を使用する、という書き方になっている模様
- `Redis の デフォルトのポートは 6379 番です。`
https://qiita.com/wind-up-bird/items/f2d41d08e86789322c71
- また、現時点ではGemfileではRedis関係のライブラリをインストールしていない（コメントアウトになっている）
https://github.com/Conovel/backend/blob/feature/CNV-66-open-api/Gemfile

Redisで何ができるかを自分はまだよくわかってないのですが、現時点ではこのままにしておいて問題なさそうに思いました。
https://envader.plus/article/10

2024-09-23 05:29 UTC, ryo-i commented on config/initializers/cors.rb
> +    origins 'http://localhost:3000' # localhost frontend url
@technokuro 
ありがとうございます！production と development で定義分けを修正しました。
ローカル環境でdocker再起動→frontend、backend間の通信でCORSエラーは発生しませんでした。

2024-09-24 11:32 UTC, azufb commented on openapigen/config/cable.yml
> +  url: redis://localhost:6379/1
@ryo-i 
そうなんですね！
承知いたしました！！
問題ないのであれば、そのままで大丈夫かと思います！！

2024-09-24 11:34 UTC, azufb approved these changes
@ryo-i @technokuro 
私はapproveです！！

2024-09-26 00:13 UTC, technokuro commented on config/initializers/cors.rb
> +    origins 'http://localhost:3000' # localhost frontend url
@ryo-i 
ありがとうございます。
https://github.com/Conovel/environment/pull/3#discussion_r1776125311
👆が、ここに関連した内容でのコメントになります。
本PRについては問題ありません。

2024-09-26 00:14 UTC, technokuro approved these changes

2024-09-28 07:14 UTC, merged