後続・パラレル投稿取得APIの詳細定義・作り込み(CNV-117)
Conovel/backend pull request #7
Opened 2024-11-14 23:47 UTC by ryo-i

## JIRAチケットURL
https://techno-kuro-novel.atlassian.net/browse/CNV-117

---
## 実装内容

### 機能要件

このセクションでは、以下URL参照先（機能要件）の記載を引用し、どの要件を満たすための実装をしたのかを記載します。
https://techno-kuro-novel.atlassian.net/wiki/spaces/Conovel/pages/3145744
なお、上記URLに含まれない実装をしている場合は、適宜参照先URLを付して、記載を引用して記載してください。
必ず製造タスクの根拠を示してください。

　例　テーブル定義Miroやその他資料

- 機能要件1：後続・パラレル投稿取得API
- 機能要件2：main投稿のみでなくparent、parent_parallel、childrenの情報も取得できる

また、上記要件資料を参照し、漏れがないことを確認したら、チェックします。

[○] 要件漏れがないことを確認済み
[] 一部懸念あり

### 非機能要件

このセクションでは、以下URL参照先（非機能要件）の記載を引用し、どの要件を満たすための実装をしたのかを記載します。
https://techno-kuro-novel.atlassian.net/wiki/spaces/Conovel/pages/1376286/_PJ
なお、上記URLに含まれない実装をしている場合は、適宜参照先URLを付して、記載を引用して記載してください。

- 非機能要件1：テスト定義＞RSpecでエラーなし

以下非機能要件を遵守すべき事項を確認しチェック
[○] CORS制約
[] XSS防止
[] CSRF防止
[] 認証中トークン
[] 広告枠

---

## テスト

[○] テストコード作成済み（C1レベル確認済み）

## 自身で確認した動作のエビデンス（スクショ等）

### 動作確認エビデンス1

postman（sentenceのパラメータが増え、さらにmain、parent、parent_parallel、childrenも含む形になっている
![スクリーンショット 2024-11-15 8 46 21](https://github.com/user-attachments/assets/4cc58a08-cefb-4774-ad17-b036de65a0d1)
![スクリーンショット 2024-11-15 8 46 32](https://github.com/user-attachments/assets/0e1c433f-5784-44d0-b86d-3a6ccebf08c4)
![スクリーンショット 2024-11-15 8 46 44](https://github.com/user-attachments/assets/8a38c0c3-c5ee-4b7f-9887-458dd7028ff8)
![スクリーンショット 2024-11-15 8 46 51](https://github.com/user-attachments/assets/4deb5e81-2ceb-482d-8eb2-30e6b6613c3d)

### 動作確認エビデンス2

---
## 結合テスト・受入テストに持ち越すテスト項目（必ず1つ以上作成）
本PullReqで洗い出し記載して、Mergeしたら、以下に整理転記する
https://techno-kuro-novel.atlassian.net/wiki/spaces/Conovel/pages/38567991

### テスト要求1

下記のライブラリを追加しています
- paranoia：データを論理削除する
- factory_bot_rails：rspec内でテストデータを生成・管理する
- database_cleaner-active_record：rspecテスト実行前にデータベースのデータをリセットする

### テスト要求2

RSpecのテストデータはテスト内でfactory_botで生成して読み込む作りにしています

### テスト要求3

2024/11/14の定例MTGで決定した「パラレル投稿」の仕様変更はまだ反映していません
下記のチケットで反映予定です
https://techno-kuro-novel.atlassian.net/browse/CNV-136

2024-11-17 20:18 UTC, technokuro requested changes
@ryo-i 
`config/routes.rb` に `sentences` の追記が必要では？

2024-11-17 20:18 UTC, technokuro commented on .rubocop.yml
>      - 'spec/requests/sentences_spec.rb'
@ryo-i 
毎回追加するのは面倒なので

`spec/**/*` や `db/migrate/**/*` などの指定にするのはどうでしょうか？

2024-11-17 20:18 UTC, technokuro commented on app/controllers/v1/sentences_controller.rb
>        result = FindSentenceService.new(params[:sentence_id]).call
@ryo-i 
動作するのはわかるのですが、どうも一貫性がありません。
冒頭で `FindSentenceService.new(params[:sentence_id]).call` としている割に、兄弟や子要素を取得するときには、`Sentence.find` を使っていて、 `FindSentenceService` の利用価値をなくしています。

`Serivice` の利用価値は、model と controller の間に立って、ロジックを整理するためにあるので、
正直、 controller は以下のコードだけで完結し、細かいロジックは `Service` で記述するべきです
また、`Service` の利用価値とパフォーマンスを向上させるために、`FindSentenceService` は `include Singleton` にすることもバックエンドでは良く行われます。
以下は、 `FindSentenceService` が `include Singleton` となっていることを前提に記載します。

```
def show
 result = FindSentenceService.instance.call(params[:sentence_id])
 if result
  render json: result, status: :ok
 else
  render nil, status: :not_found
 end
end
```

以上のように、controller はあくまで処理のコールと返却値の振り分けのみに徹し、整形ロジックは Service に任せるべきです

そうでなければ、 Service を作る意味がないので、 controller に書くならば、 Service は不要の考え方になります
元々 Service を作ろうとした経緯に基づき、再検討をお願いします。

なお、口述　※　でも記載しましたが、 何も関連する情報を DB から都度取得する必要はなくて、アソシエーションで取得可能なので、 ViewSentence コンポーネントを構成する情報をアソシエーションで表現してしまえばいいと思います。

2024-11-17 20:18 UTC, technokuro commented on app/models/sentence.rb
> +  has_many :child_sentences, class_name: 'Sentence', foreign_key: 'parent_sentence_id'
@ryo-i 
APIパラメタに合わせて `children` でよいと思います

2024-11-17 20:18 UTC, technokuro commented on app/controllers/v1/sentences_controller.rb
> +      User.find(user_id)
@ryo-i 
‘models/sentence.rb` でアソシエーションしているので、わざわざ `User.find` する必要はなさそうですね
同様の箇所を ※ とします

2024-11-17 20:18 UTC, technokuro commented on app/controllers/v1/sentences_controller.rb
> +        good: Evaluation.where(sentence_id:, evaluation: 'good').count,
※

2024-11-17 20:18 UTC, technokuro commented on app/controllers/v1/sentences_controller.rb
> +      Sentence.find_by(sentence_id: parent_sentence_id)
※

2024-11-17 20:18 UTC, technokuro commented on app/controllers/v1/sentences_controller.rb
> +      parent_sentence = find_parent_sentence(sentence.parent_sentence_id)
※

2024-11-17 20:18 UTC, technokuro commented on app/controllers/v1/sentences_controller.rb
> +      Sentence.where(parent_sentence_id: parent_sentence.parent_sentence_id)
※

2024-11-17 20:18 UTC, technokuro commented on app/controllers/v1/sentences_controller.rb
> +      Sentence.where(parent_sentence_id:)
※

2024-11-17 20:18 UTC, technokuro commented on app/controllers/v1/sentences_controller.rb
> +      user ||= find_user(sentence.sentence_user_id)
@ryo-i 
User に対して N+1問題発生しています

sentence の user と、sentence の evaluation の user とも、重複がある可能性があります

includes or join を使いましょう

2024-11-19 11:43 UTC, technokuro commented on app/models/sentence.rb
>    def self.find_by_id(sentence_id)
deleted_at is null の考慮が必要

2024-11-20 22:16 UTC, ryo-i reviewed
メモを追記
- MTGで話に出た追加修正
- 誤って非表示(Resolve conversation)になってしまったコメント

2024-11-20 22:16 UTC, ryo-i commented on app/controllers/v1/sentences_controller.rb
> +
メモ：

※下記のコメントがResolve conversationで非表示なってしまった、、

userに対してn + 1問題が発生しているため、includesを使って解決する
 
 As Isのコード
```
      user ||= find_user(sentence.sentence_user_id)
      evaluation_counts ||= fetch_evaluation_counts(sentence.sentence_id)
```

2024-11-20 22:16 UTC, ryo-i commented on app/controllers/v1/sentences_controller.rb
> +      }
MEMO：
goodとstayのカウントを一度で取得できる形を検討にする（MTGにて）

2024-11-20 23:11 UTC, ryo-i commented on .rubocop.yml
>      - 'spec/requests/sentences_spec.rb'
@technokuro 
`*`を使った汎用的な書き方に修正しました！

2024-11-20 23:12 UTC, ryo-i commented on app/controllers/v1/sentences_controller.rb
>        result = FindSentenceService.new(params[:sentence_id]).call
@technokuro 
`includes`で一度に取得する形に書き換えました！

2024-11-20 23:13 UTC, ryo-i commented on app/models/sentence.rb
> +  has_many :child_sentences, class_name: 'Sentence', foreign_key: 'parent_sentence_id'
@technokuro 
`children`に変更しました。親投稿の方も`parent`に変更しました。

2024-11-20 23:13 UTC, ryo-i commented on app/controllers/v1/sentences_controller.rb
> +      User.find(user_id)
@technokuro
includesで一度に取得する形に書き換えました！

2024-11-20 23:13 UTC, ryo-i commented on app/controllers/v1/sentences_controller.rb
> +        good: Evaluation.where(sentence_id:, evaluation: 'good').count,
@technokuro
includesで一度に取得する形に書き換えました！

2024-11-20 23:13 UTC, ryo-i commented on app/controllers/v1/sentences_controller.rb
> +      Sentence.find_by(sentence_id: parent_sentence_id)
@technokuro
includesで一度に取得する形に書き換えました！

2024-11-20 23:13 UTC, ryo-i commented on app/controllers/v1/sentences_controller.rb
> +      parent_sentence = find_parent_sentence(sentence.parent_sentence_id)
@technokuro
includesで一度に取得する形に書き換えました！

2024-11-20 23:13 UTC, ryo-i commented on app/controllers/v1/sentences_controller.rb
> +      Sentence.where(parent_sentence_id: parent_sentence.parent_sentence_id)
@technokuro
includesで一度に取得する形に書き換えました！

2024-11-20 23:13 UTC, ryo-i commented on app/controllers/v1/sentences_controller.rb
> +      Sentence.where(parent_sentence_id:)
@technokuro
includesで一度に取得する形に書き換えました！

2024-11-20 23:13 UTC, ryo-i commented on app/controllers/v1/sentences_controller.rb
> +      user ||= find_user(sentence.sentence_user_id)
@technokuro
includesで一度に取得する形に書き換えました！

2024-11-20 23:16 UTC, ryo-i commented on app/models/sentence.rb
>    def self.find_by_id(sentence_id)
論理削除を適用する`acts_as_paranoid`を追記しました
- `sentence`以外の`deleted_at`があるモデルにも適用しました
- 通常の`All`、`find`などの検索では論理削除のレコードは除外されます
- `with_deleted`で論理削除されたレコードも含めて検索
- `only_deleted`で論理削除されたレコードのみ検索

2024-11-20 23:17 UTC, ryo-i commented on app/controllers/v1/sentences_controller.rb
> +      }
@technokuro 
goodとstayのカウントを一度で取得できる形に修正しました！

2024-11-20 23:18 UTC, ryo-i commented
@technokuro cc @azufb 
レビューのフィードバックおよび先日MTGでお話しした内容を修正しました！ご確認お願いいたしますmm

※別チケットのパラレル投稿の修正はまだ適用しておりませんmm

2024-11-21 04:05 UTC, technokuro requested changes
もう少しです💦

2024-11-21 04:05 UTC, technokuro commented on app/controllers/v1/sentences_controller.rb
> +      @sentence = Sentence.includes(:user, :evaluations, :children, parent: :parent).find_by_id(params[:sentence_id])
@ryo-i 
`ApplicationController` 継承クラスは、クライアントリクエストのたびにインスタンス化されますから、大きな問題にはなりませんが、マルチスレッド環境下においてはスレッドセーフではなくなります。
無暗にインスタンス変数を利用することは避けるべきです。

また、このインスタンス変数はこの関数以外で使われていないため、インスタンス変数である必要がありません。
ローカル変数にしてください

2024-11-21 04:05 UTC, technokuro commented on app/controllers/v1/sentences_controller.rb
> +    def render_success_response(sentence)
ここくらいは L18 に書いてもいいと思いますけどね💦
あまりあっちこっちに飛ぶのは可読性的に避けたいですね

2024-11-21 04:05 UTC, technokuro commented on app/controllers/v1/sentences_controller.rb
> +      evaluation_counts ||= fetch_evaluation_counts(sentence)
前段ですでに `fetch_evaluation_counts` を [L37](https://github.com/Conovel/backend/pull/7/files#diff-7da8353572667335d35f736e5752bdd0ed09596b505d79130359ad3119600bfcR37) で実施済みなので、冗長に実施してしまっています。

従って、N+1問題が引き続き発生しています

2024-11-21 04:05 UTC, technokuro commented on app/controllers/v1/sentences_controller.rb
> +      @sentence = Sentence.includes(:user, :evaluations, :children, parent: :parent).find_by_id(params[:sentence_id])
ちなみに、すでに、`parent_parallel` は不要だと思っています。

2024-11-21 04:05 UTC, technokuro commented on app/controllers/v1/sentences_controller.rb
> +      parent_sentence.parent.children.where.not(sentence_id: parent_sentence.sentence_id)
@ryo-i 
参考情報

すでに includes や join で取得された値（Eager Loading）に対して、 where を記載すると、再度SQLクエリが実行されます。

そのつもりであれば差し支えありません

2024-11-26 20:04 UTC, technokuro commented on app/controllers/v1/sentences_controller.rb
> +        :children
@ryo-i 
`parallels` `children` を `includes` すると、以下のような事前ロードとなります。
- 自分の親 sentence は事前ロードするが、親の user と evaluation は事前ロードしない
- children も同様

そのため、以下のような記載にして、事前ロードすることなります。

```
Sentence.includes(
        :user,
        :evaluations,
        :parent,
        parallels: [:user :evaluation],
        children: [:user :evaluation]
)
```
もっとも N+1 が発生しやすいのが parallels と children なので、ここを押さえておきたいですね

2024-11-26 22:58 UTC, ryo-i commented on app/controllers/v1/sentences_controller.rb
> +        :children
@technokuro 
ありがとうございます！最終的に下記の形に修正しました。ご確認お願いしますmm

- N+1問題が生じていることが自力で判断しづらく、`bullet`ライブラリをインストール（←定番ライブラリのようです）
- bulletのログ`bullet.log`でN+1の発生状況を確認（←ここにログが出なくなるとN+1が解消している）
- それでも確証が得られず`development.log`で実行されているSQL文も確認
- 下記にAs IsとTo Beの比較を掲載しますので、ご確認お願いしますmm

※疑問が残っているのが、`user`と`evaluations`共に`sentences`とは別のモデルで`included`で事前取得した方が良さそうに思うのですが、ログでは`evaluations`の方は事前取得が不要になっていることでした（この違いがなぜ起こっているのか）

N+1が発生については私もクロさんのように自力で判断できるようになりたいです（下記の確認方法でOKなのか確証が得られていないですが、、）

### 修正前
`backend/app/controllers/v1/sentences_controller.rb`
```
    def find_sentence(sentence_id)
      Sentence.includes(
        :user,
        :evaluations,
        :parent,
        :parallels,
        :children
      ).find_by_id(sentence_id)
    end
```
- `parallels`や`children`の中でも`user`、`evaluation`を事前取得する必要がありそう

`backend/log/bullet.log`
```
2024-11-26 21:41:17[WARN] user: root
GET /v1/sentences/3
USE eager loading detected
  Sentence => [:user]
  Add to your query: .includes([:user])
Call stack
  /app/app/controllers/v1/sentences_controller.rb:70:in `build_sentence_response'
  /app/app/controllers/v1/sentences_controller.rb:91:in `block in build_sentence_responses'
  /app/app/controllers/v1/sentences_controller.rb:90:in `map'
  /app/app/controllers/v1/sentences_controller.rb:90:in `build_sentence_responses'
  /app/app/controllers/v1/sentences_controller.rb:101:in `build_response'
  /app/app/controllers/v1/sentences_controller.rb:19:in `show'

2024-11-26 21:41:17[WARN] user: root
GET /v1/sentences/3
AVOID eager loading detected
  Sentence => [:evaluations]
  Remove from your query: .includes([:evaluations])
Call stack
  /app/app/models/sentence.rb:35:in `find_by_id'
  /app/app/controllers/v1/sentences_controller.rb:40:in `find_sentence'
  /app/app/controllers/v1/sentences_controller.rb:16:in `show'
```
- `user`：`USE eager loading detected`→includedに追加する必要あり
- `evaluations`：`AVOID eager loading detected`→逆にincludedから除外する必要あり？

`backend/log/development.log`
```
Started GET "/v1/sentences/3" for 192.168.65.1 at 2024-11-26 22:18:20 +0000
Processing by V1::SentencesController#show as HTML
  Parameters: {"sentence_id"=>"3"}
  [1m[36mSentence Load (0.3ms)[0m  [1m[34mSELECT `sentences`.* FROM `sentences` WHERE `sentences`.`deleted_at` IS NULL AND `sentences`.`sentence_id` = 3 LIMIT 1[0m
  ↳ app/models/sentence.rb:35:in `find_by_id'
  [1m[36mUser Load (0.2ms)[0m  [1m[34mSELECT `users`.* FROM `users` WHERE `users`.`deleted_at` IS NULL AND `users`.`user_id` = 1[0m
  ↳ app/models/sentence.rb:35:in `find_by_id'
  [1m[36mEvaluation Load (0.2ms)[0m  [1m[34mSELECT `evaluations`.* FROM `evaluations` WHERE `evaluations`.`deleted_at` IS NULL AND `evaluations`.`sentence_id` = 3[0m
  ↳ app/models/sentence.rb:35:in `find_by_id'
  [1m[36mSentence Load (0.1ms)[0m  [1m[34mSELECT `sentences`.* FROM `sentences` WHERE `sentences`.`deleted_at` IS NULL AND `sentences`.`sentence_id` = 2[0m
  ↳ app/models/sentence.rb:35:in `find_by_id'
  [1m[36mSentence Load (0.2ms)[0m  [1m[34mSELECT `sentences`.* FROM `sentences` WHERE `sentences`.`deleted_at` IS NULL AND `sentences`.`sentence_id` != 3 AND `sentences`.`parent_sentence_id` = 2[0m
  ↳ app/models/sentence.rb:35:in `find_by_id'
  [1m[36mSentence Load (0.1ms)[0m  [1m[34mSELECT `sentences`.* FROM `sentences` WHERE `sentences`.`deleted_at` IS NULL AND `sentences`.`parent_sentence_id` = 3[0m
  ↳ app/models/sentence.rb:35:in `find_by_id'
  [1m[36mEvaluation Count (0.2ms)[0m  [1m[34mSELECT COUNT(*) AS `count_all`, `evaluations`.`evaluation` AS `evaluations_evaluation` FROM `evaluations` WHERE `evaluations`.`deleted_at` IS NULL AND `evaluations`.`sentence_id` = 3 GROUP BY `evaluations`.`evaluation`[0m
  ↳ app/controllers/v1/sentences_controller.rb:52:in `fetch_evaluation_counts'
  [1m[36mUser Load (0.1ms)[0m  [1m[34mSELECT `users`.* FROM `users` WHERE `users`.`deleted_at` IS NULL AND `users`.`user_id` = 2 LIMIT 1[0m
  ↳ app/controllers/v1/sentences_controller.rb:64:in `build_sentence_response'
  [1m[36mEvaluation Count (0.3ms)[0m  [1m[34mSELECT COUNT(*) AS `count_all`, `evaluations`.`evaluation` AS `evaluations_evaluation` FROM `evaluations` WHERE `evaluations`.`deleted_at` IS NULL AND `evaluations`.`sentence_id` = 2 GROUP BY `evaluations`.`evaluation`[0m
  ↳ app/controllers/v1/sentences_controller.rb:52:in `fetch_evaluation_counts'
  [1m[36mCACHE User Load (0.0ms)[0m  [1m[34mSELECT `users`.* FROM `users` WHERE `users`.`deleted_at` IS NULL AND `users`.`user_id` = 2 LIMIT 1[0m
  ↳ app/controllers/v1/sentences_controller.rb:64:in `build_sentence_response'
  [1m[36mEvaluation Count (0.2ms)[0m  [1m[34mSELECT COUNT(*) AS `count_all`, `evaluations`.`evaluation` AS `evaluations_evaluation` FROM `evaluations` WHERE `evaluations`.`deleted_at` IS NULL AND `evaluations`.`sentence_id` = 11 GROUP BY `evaluations`.`evaluation`[0m
  ↳ app/controllers/v1/sentences_controller.rb:52:in `fetch_evaluation_counts'
  [1m[36mUser Load (0.1ms)[0m  [1m[34mSELECT `users`.* FROM `users` WHERE `users`.`deleted_at` IS NULL AND `users`.`user_id` = 3 LIMIT 1[0m
  ↳ app/controllers/v1/sentences_controller.rb:64:in `build_sentence_response'
  [1m[36mEvaluation Count (0.1ms)[0m  [1m[34mSELECT COUNT(*) AS `count_all`, `evaluations`.`evaluation` AS `evaluations_evaluation` FROM `evaluations` WHERE `evaluations`.`deleted_at` IS NULL AND `evaluations`.`sentence_id` = 12 GROUP BY `evaluations`.`evaluation`[0m
  ↳ app/controllers/v1/sentences_controller.rb:52:in `fetch_evaluation_counts'
  [1m[36mUser Load (0.1ms)[0m  [1m[34mSELECT `users`.* FROM `users` WHERE `users`.`deleted_at` IS NULL AND `users`.`user_id` = 4 LIMIT 1[0m
  ↳ app/controllers/v1/sentences_controller.rb:64:in `build_sentence_response'
  [1m[36mEvaluation Count (0.1ms)[0m  [1m[34mSELECT COUNT(*) AS `count_all`, `evaluations`.`evaluation` AS `evaluations_evaluation` FROM `evaluations` WHERE `evaluations`.`deleted_at` IS NULL AND `evaluations`.`sentence_id` = 13 GROUP BY `evaluations`.`evaluation`[0m
  ↳ app/controllers/v1/sentences_controller.rb:52:in `fetch_evaluation_counts'
Completed 200 OK in 57ms (Views: 0.5ms | ActiveRecord: 12.2ms | Allocations: 33589)


user: root
GET /v1/sentences/3
USE eager loading detected
  Sentence => [:user]
  Add to your query: .includes([:user])
Call stack
  /app/app/controllers/v1/sentences_controller.rb:64:in `build_sentence_response'
  /app/app/controllers/v1/sentences_controller.rb:84:in `block in build_sentence_responses'
  /app/app/controllers/v1/sentences_controller.rb:83:in `map'
  /app/app/controllers/v1/sentences_controller.rb:83:in `build_sentence_responses'
  /app/app/controllers/v1/sentences_controller.rb:94:in `build_response'
  /app/app/controllers/v1/sentences_controller.rb:19:in `show'


user: root
GET /v1/sentences/3
AVOID eager loading detected
  Sentence => [:evaluations]
  Remove from your query: .includes([:evaluations])
Call stack
  /app/app/models/sentence.rb:35:in `find_by_id'
  /app/app/controllers/v1/sentences_controller.rb:35:in `find_sentence'
  /app/app/controllers/v1/sentences_controller.rb:16:in `show'
```
- `user`と`evaluations`が`sentences`とは別で実行されている

### 修正1
`backend/app/controllers/v1/sentences_controller.rb`
```
    def find_sentence(sentence_id)
      Sentence.includes(
        :user,
        :evaluations,
        :parent,
        parallels: [:user, :evaluations],
        children: [:user, :evaluations]
      ).find_by_id(sentence_id)
    end
```
- `parallels`と`children`の中でも`user`と`:evaluations`を取得

`backend/log/bullet.log`
```
2024-11-26 21:44:35[WARN] user: root
GET /v1/sentences/3
AVOID eager loading detected
  Sentence => [:evaluations]
  Remove from your query: .includes([:evaluations])
Call stack
  /app/app/models/sentence.rb:35:in `find_by_id'
  /app/app/controllers/v1/sentences_controller.rb:35:in `find_sentence'
  /app/app/controllers/v1/sentences_controller.rb:16:in `show'
```
- `user`の警告はなくなる
- `evaluations`：`AVOID eager loading detected`は残っている

`backend/log/development. [...]

2024-12-01 23:43 UTC, ryo-i commented on app/controllers/v1/sentences_controller.rb
> +        :children
@technokuro 
再度修正しました！ご確認お願いしますmm
https://github.com/Conovel/backend/pull/7/commits/361820a56ee8bb951daef980bb2a76b8d8b9a0f4

前回までの問題点`fetch_evaluation_counts`の下記のところで実行している`group`や`count`を実行すると、事前に取得した`evaluations`が参照されず、新たにSQLが実行されることがわかった
```
counts = sentence.evaluations.group(:evaluation).count
```

下記のように`each_with_object`を実行すると事前に取得した`evaluations`が参照されることがわかった
```
counts = sentence.evaluations.each_with_object(Hash.new(0)) do |evaluation, hash|
   hash[evaluation.evaluation] += 1
end
``` 

`backend/log/development.log`の結果
```
 Started GET "/v1/sentences/3" for 192.168.65.1 at 2024-12-01 23:24:44 +0000
Processing by V1::SentencesController#show as HTML
  Parameters: {"sentence_id"=>"3"}
  [1m[36mSentence Load (3.7ms)[0m  [1m[34mSELECT `sentences`.* FROM `sentences` WHERE `sentences`.`deleted_at` IS NULL AND `sentences`.`sentence_id` = 3 LIMIT 1[0m
  ↳ app/models/sentence.rb:35:in `find_by_id'
  [1m[36mUser Load (0.9ms)[0m  [1m[34mSELECT `users`.* FROM `users` WHERE `users`.`deleted_at` IS NULL AND `users`.`user_id` = 1[0m
  ↳ app/models/sentence.rb:35:in `find_by_id'
  [1m[36mEvaluation Load (2.6ms)[0m  [1m[34mSELECT `evaluations`.* FROM `evaluations` WHERE `evaluations`.`deleted_at` IS NULL AND `evaluations`.`sentence_id` = 3[0m
  ↳ app/models/sentence.rb:35:in `find_by_id'
  [1m[36mSentence Load (0.2ms)[0m  [1m[34mSELECT `sentences`.* FROM `sentences` WHERE `sentences`.`deleted_at` IS NULL AND `sentences`.`sentence_id` = 2[0m
  ↳ app/models/sentence.rb:35:in `find_by_id'
  [1m[36mSentence Load (0.2ms)[0m  [1m[34mSELECT `sentences`.* FROM `sentences` WHERE `sentences`.`deleted_at` IS NULL AND `sentences`.`parent_sentence_id` = 3[0m
  ↳ app/models/sentence.rb:35:in `find_by_id'
  [1m[36mSentence Load (0.3ms)[0m  [1m[34mSELECT `sentences`.* FROM `sentences` WHERE `sentences`.`deleted_at` IS NULL AND `sentences`.`sentence_id` != 3 AND `sentences`.`parent_sentence_id` = 2[0m
  ↳ app/models/sentence.rb:35:in `find_by_id'
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT `users`.* FROM `users` WHERE `users`.`deleted_at` IS NULL AND `users`.`user_id` IN (2, 3, 4)[0m
  ↳ app/models/sentence.rb:35:in `find_by_id'
  [1m[36mEvaluation Load (0.5ms)[0m  [1m[34mSELECT `evaluations`.* FROM `evaluations` WHERE `evaluations`.`deleted_at` IS NULL AND `evaluations`.`sentence_id` IN (11, 12, 13)[0m
  ↳ app/models/sentence.rb:35:in `find_by_id'
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT `users`.* FROM `users` WHERE `users`.`deleted_at` IS NULL AND `users`.`user_id` = 2 LIMIT 1[0m
  ↳ app/controllers/v1/sentences_controller.rb:67:in `build_sentence_response'
  [1m[36mEvaluation Load (0.5ms)[0m  [1m[34mSELECT `evaluations`.* FROM `evaluations` WHERE `evaluations`.`deleted_at` IS NULL AND `evaluations`.`sentence_id` = 2[0m
  ↳ app/controllers/v1/sentences_controller.rb:52:in `each_with_object'
Completed 200 OK in 64ms (Views: 0.4ms | ActiveRecord: 9.5ms | Allocations: 15038)
```
 - evaluationsの実行回数が3回になり、`AVOID eager loading detected`の警告も出ない

2024-12-02 00:17 UTC, technokuro requested changes
@ryo-i 
もう少し！
細かい確認事項を記載しました。

2024-12-02 00:17 UTC, technokuro commented on Gemfile
> +  gem 'paranoia', '~> 2.4'
@ryo-i 
これって development test セクションじゃなくて、本番でも使いませんか？

2024-12-02 00:17 UTC, technokuro commented on .rubocop.yml
> +    - 'db/migrate/**/*'
@ryo-i @azufb 
BlockLength が 30 の制約のところ
MethodLength がデフォルトの 10 というのは なんか違和感を感じます。

事実 disabled にしている箇所もあるので、ここは、BlockLength よりも長いものにしてはどうだろうか？

2024-12-02 00:17 UTC, technokuro commented on app/controllers/v1/sentences_controller.rb
> +      user = sentence.user
これって可読性のため？

2024-12-02 00:17 UTC, technokuro commented on app/controllers/v1/sentences_controller.rb
> +    def format_time(time)
これって共通処理にしてしまいたいですね

2024-12-02 23:29 UTC, ryo-i reviewed
@technokuro cc @azufb 
ありがとうございます。
修正&コメントしました！ご確認お願いしますmm

2024-12-02 23:29 UTC, ryo-i commented on app/controllers/v1/sentences_controller.rb
> +      user = sentence.user
@technokuro 
はい、`sentence.user`が2回実行されていたのでここでまとめました。
N+1が解決できない時に`user`の処理をなるべく減らした方がいいかと思いまとめた部分もあります。
ただ、N+1とは関係なさそうでしたし、`sentence.user`が2回程度なら下のところで直接書いてもいいかもですね（？）

2024-12-02 23:29 UTC, ryo-i commented on Gemfile
> +  gem 'paranoia', '~> 2.4'
@technokuro 
おしゃる通りでした！追加する場所を間違えていたようです。
直下でinstallされるように修正しました！
https://github.com/Conovel/backend/pull/7/commits/ba1f6ad7515f63c3bf02e49b685c07f9e34d0bd2

2024-12-02 23:29 UTC, ryo-i commented on .rubocop.yml
> +    - 'db/migrate/**/*'
@technokuro cc @azufb 
40行に変更してみました！
https://github.com/Conovel/backend/pull/7/commits/4369acf577c1f22c2a5bb019c05ee3c6c22cbda5
メソッドの適切な行数ってどのくらいですかね？（50行くらいまでは許容？）

`backend/app/controllers/v1/sentences_controller.rb`の`build_sentence_response`につけていた行数制限のコメント`# rubocop:disable Metrics/MethodLength`を削除してみましたがrubocopでエラーにならなくなりました。

> MethodLength がデフォルトの 10 というのは なんか違和感を感じます。

rubocopの`MethodLength`のデフォルトって10行なんですね、、
https://github.com/rubocop/rubocop/blob/master/config/default.yml#L2710
結構MethodLengthで叱られてメソッドを分割していました。。（使い回しがないような処理でも）

2024-12-02 23:29 UTC, ryo-i commented on app/controllers/v1/sentences_controller.rb
> +    def format_time(time)
@technokuro 
修正しました。
https://github.com/Conovel/backend/pull/7/commits/06f69d3ff48c6929d76b449206ac6fbde3401d16

他のファイルでの共通処理できるように別ファイルにしてみました！
共通処理のファイルは`helpers`ディレクトリの中に追加していこうと思います。

2024-12-05 11:42 UTC, technokuro commented on .rubocop.yml
> +    - 'db/migrate/**/*'
いいと思います

2024-12-05 11:42 UTC, technokuro commented on app/controllers/v1/sentences_controller.rb
> +      user = sentence.user
確認したかっただけです。
OKです。

2024-12-05 11:43 UTC, technokuro commented on Gemfile
> +  gem 'paranoia', '~> 2.4'
OKです！

2024-12-05 11:44 UTC, technokuro commented on app/controllers/v1/sentences_controller.rb
> +    def format_time(time)
NICE！

2024-12-05 11:46 UTC, technokuro approved these changes
![LGTM](https://image.lgtmoon.dev/312116)

2024-12-05 13:03 UTC, azufb approved these changes

2024-12-05 13:03 UTC, merged